// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/UpdaterStatus copy.vue')['default']
    DnsStatus: typeof import('./src/components/DnsStatus.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IEosIconsIpOutlined: typeof import('~icons/eos-icons/ip-outlined')['default']
    IHealthiconsCityOutline: typeof import('~icons/healthicons/city-outline')['default']
    IHeroiconsOutlineStatusOnline: typeof import('~icons/heroicons-outline/status-online')['default']
    IMaterialSymbolsCloudSyncOutline: typeof import('~icons/material-symbols/cloud-sync-outline')['default']
    IMaterialSymbolsShield: typeof import('~icons/material-symbols/shield')['default']
    IRiEarthLine: typeof import('~icons/ri/earth-line')['default']
    ISimpleIconsOpenvpn: typeof import('~icons/simple-icons/openvpn')['default']
    ISimpleIconsWireguard: typeof import('~icons/simple-icons/wireguard')['default']
    OpenVPN: typeof import('./src/components/settings/OpenVPN.vue')['default']
    Provider: typeof import('./src/components/settings/Provider.vue')['default']
    PublicIp: typeof import('./src/components/PublicIp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdaterStatus: typeof import('./src/components/UpdaterStatus.vue')['default']
    VpnSettings: typeof import('./src/components/VpnSettings.vue')['default']
    Wireguard: typeof import('./src/components/settings/Wireguard.vue')['default']
  }
}
